# Generated by Django 5.1.6 on 2026-07-09 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0003_fcmdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlsoViewedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('also_viewed_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_with', to='backend.course')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='also_viewed', to='backend.course')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['course'], name='analytics_a_course__00c848_idx')],
                'unique_together': {('course', 'also_viewed_course')},
            },
        ),
        migrations.CreateModel(
            name='SimilarCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_courses', to='backend.course')),
                ('similar_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='backend.course')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['course'], name='analytics_s_course__58b712_idx')],
                'unique_together': {('course', 'similar_course')},
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('course', 'Course'), ('subject', 'Subject'), ('note', 'Note')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('view', 'View'), ('enroll', 'Enroll'), ('download', 'Download'), ('click_recommendation', 'Click Recommendation')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='analytics_u_user_id_e7755f_idx'), models.Index(fields=['item_type', 'item_id'], name='analytics_u_item_ty_c5c594_idx'), models.Index(fields=['created_at'], name='analytics_u_created_aac3ff_idx')],
            },
        ),
    ]
