# Generated by Django 5.1.6 on 2026-01-26 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=30)),
                ('item_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('view', 'View'), ('enroll', 'Enroll'), ('download', 'Download'), ('click_recommendation', 'Click Recommendation')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['item_type', 'item_id', 'action'], name='analytics_u_item_ty_b36a28_idx'), models.Index(fields=['user', 'action', 'created_at'], name='analytics_u_user_id_fc9f46_idx'), models.Index(fields=['created_at'], name='analytics_u_created_aac3ff_idx')],
            },
        ),
    ]
