# Generated by Django 5.1.6 on 2026-01-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveIntegerField(db_index=True)),
                ('similar_course_id', models.PositiveIntegerField(db_index=True)),
                ('score', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['course_id', '-score'], name='analytics_s_course__ce01ea_idx')],
                'unique_together': {('course_id', 'similar_course_id')},
            },
        ),
    ]
