# Generated by Django 5.1.6 on 2026-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_similarcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlsoViewedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveIntegerField(db_index=True)),
                ('also_viewed_course_id', models.PositiveIntegerField(db_index=True)),
                ('score', models.FloatField(default=0.0)),
            ],
            options={
                'indexes': [models.Index(fields=['course_id', '-score'], name='analytics_a_course__e32907_idx')],
                'unique_together': {('course_id', 'also_viewed_course_id')},
            },
        ),
    ]
