# Generated by Django 5.1.6 on 2025-08-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('sports', 'Sports'), ('education', 'Education'), ('lifestyle', 'Lifestyle'), ('news', 'News')], default='tech', max_length=50),
        ),
    ]
