# Generated by Django 5.1.6 on 2026-01-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquiry', '0002_contactenquiry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('done', 'Done')], default='pending', max_length=10),
        ),
    ]
